services:
  react-app:
    build:
      context: ./react-app
    ports:
      - 3000:3000
    container_name: react-app
    stdin_open: true
    volumes:
      - ./react-app:/usr/src/app/react-app

  fastapi:
    build:
      context: ./fastapi
    ports:
      - 8000:8000
    container_name: fastapi
    volumes:
      - ./fastapi:/usr/src/app/fastapi
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo/database:/usr/src/app/mongo/database
    ports:
      - 27017:27017
    restart: unless-stopped
